#install.packages("EpiEstim", repos = "http://cran.us.r-project.org")
#install.packages("remotes", repos = "http://cran.us.r-project.org")
#library(remotes)
#remotes::install_github("dajmcdon/rtestim")
#install.packages("EpiLPS", repos = "http://cran.us.r-project.org")
#install.packages("data.table", repos = "http://cran.us.r-project.org")
#install.packages("dplyr", repos = "http://cran.us.r-project.org")
#install.packages("tidyr", repos = "http://cran.us.r-project.org")
#install.packages("testthat", repos = "http://cran.us.r-project.org")
#install.packages("batchtools", repos = "http://cran.us.r-project.org")
#install.packages("microbenchmark", repos = "http://cran.us.r-project.org")

library(EpiEstim)
library(rtestim)
library(EpiLPS)
library(EpiNow2)
library(data.table)
library(dplyr)
library(tidyr)
library(testthat)
library(batchtools)
library(microbenchmark)

source('src/exp/EpiFilter-master/R files/main/epiFilter.R')
source('src/exp/EpiFilter-master/R files/main/epiSmoother.R')