#library(remotes)
#remotes::install_github("dajmcdon/rtestim")
#remotes::install_github("mrc-ide/EpiEstim")
## install.packages("EpiEstim", repos = "http://cran.us.r-project.org")
#install.packages("remotes", repos = "http://cran.us.r-project.org")
#install.packages("EpiLPS", repos = "http://cran.us.r-project.org")
#install.packages("data.table", repos = "http://cran.us.r-project.org")
#install.packages("dplyr", repos = "http://cran.us.r-project.org")
#install.packages("tidyr", repos = "http://cran.us.r-project.org")
#install.packages("testthat", repos = "http://cran.us.r-project.org")
#install.packages("batchtools", repos = "http://cran.us.r-project.org")
#remotes::install_github("mllg/batchtools")
#install.packages("microbenchmark", repos = "http://cran.us.r-project.org")

library(EpiEstim)
library(rtestim)
library(EpiLPS)
library(EpiNow2)
library(data.table)
library(dplyr)
library(tidyr)
library(testthat)
library(batchtools)
library(microbenchmark)

source(here::here('src/exp_cluster/epiFilter.R'))
source(here::here('src/exp_cluster/epiSmoother.R'))
